### ISSUE TITLE
snmpwalk?

### ISSUE THREAD

**Issue by admover** [k-sone/snmpgo#19]
how can i use snmpwalk? 
thk. ^^

**Comment by k-sone** [comment]
If SNMP version is v2c or v3, you can use `snmpgo.SNMP.GetBulkWalk` function instead.

**Comment by geoffgarside** [comment]
When using bulk walk its worth setting both the nonRepeaters and maxRepetitions to none 0 values as some devices such as Dell Force10 switches don't use consecutive OIDs in tables, so if you had `nonRepeaters=0,maxRepetitions=40` you may only get part of the table you want to retrieve. I usually ended up setting both values to 40. A `GETNEXT` based walk doesn't suffer from this issue.

**Comment by k-sone** [comment]
@geoffgarside Thank you for sharing your experience.

I thought that nobody would use it, but I will consider implementation if there is demand.
