### ISSUE TITLE
Err: integer not minimally-encoded

### ISSUE THREAD

**Issue by kzdev** [k-sone/snmpgo#20]
I always use this library. thanks.
I'm not good at English, so I'm sorry if it is difficult for you to understand my English.

in this case oid response, 

```
Response: .1.3.6.1.4.1.2011.6.128.1.1.2.51.1.4.4194304000.1 : -741 : Integer 
```

Failed to Unmarshal Pdu, cause `asn1: structure error: integer not minimally-encoded`

what would be a good way to do it?

**Comment by k-sone** [comment]
Thanks for the report!

> I'm not good at English, so I'm sorry if it is difficult for you to understand my English.

Me too :smile: 

I need more information. Would you please paste the result of the following code?
```go
package main

import (
        "log"

        "github.com/k-sone/snmpgo"
)

func main() {
        snmp, err := snmpgo.NewSNMP(snmpgo.SNMPArguments{
                // TODO Replace with your environment
                Version:   snmpgo.V2c,
                Address:   "127.0.0.1:161",
                Retries:   1,
                Community: "public",
        })
        if err != nil {
                log.Fatalln(err)
        }

        oids, _ := snmpgo.NewOids([]string{"1.3.6.1.4.1.2011.6.128.1.1.2.51.1.4.4194304000.1"})

        if err = snmp.Open(); err != nil {
                log.Fatalln(err)
        }
        defer snmp.Close()

        pdu, err := snmp.GetRequest(oids)
        switch e := err.(type) {
        case nil:
        case *snmpgo.MessageError:
                log.Println(e.Error())
                log.Fatalln(e.Detail)
        default:
                log.Fatalln(err)
        }

        log.Println(pdu)
}
```

**Comment by kzdev** [comment]
Thank you for your reply.
please see the result. 

```
2017/03/29 18:38:34 Failed to Unmarshal Pdu, cause `asn1: structure error: integer not minimally-encoded`
2017/03/29 18:38:34 Pdu Bytes - [a2 2e 02 04 39 0c 42 d4 02 01 00 02 01 00 30 20 30 1e 06 16 2b 06 01 04 01 8f 5b 06 81 00 01 01 02 33 01 04 8f d0 80 80 00 00 02 04 ff ff fd 1d]
exit status 1

```

**Comment by k-sone** [comment]
Thanks.

Strictly speaking, I think that it is a bug in the SNMP device.
The last 6 bytes(02 04 ff ff fd 1d) do not conform to the ASN.1 Basic Encoding Rules. (for details, refer to chapter 8.3.2 of [ITU-T X.690](https://www.itu.int/rec/T-REC-X.690/))

Ummm. Please wait for a few days.

**Comment by k-sone** [comment]
Sorry, I could not think of a good workaround. It is best to report a bug to the manufacturer and fix it.

There are the following way, but I do not recommend it.

1. Fork repositories(github.com/geoffgarside/ber and github.com/k-sone/snmpgo) to your account
2. Comment out [here lines](https://github.com/geoffgarside/ber/blob/master/ber.go#L66-L68) in your ber repository
3. Replace ber import path in your snmpgo repository(github.com/geoffgarside/ber to github.com/\<your_account\>/ber)

If you are going to try, you need to take full responsibility for your action.

**Comment by kzdev** [comment]
Thank you for investigation.
I understand that it is a bug of equipment.

i will investigate here and consider modification.
thank you so much.
