### ISSUE TITLE
len(VarBinds) = 1 for a SNMP query that should return many more items

### ISSUE THREAD

**Issue by computerphysicslab** [k-sone/snmpgo#28]
When using github.com/k-sone/snmpgo code as SNMP agent, it works very well for single-item requests, but I cannot get the expected result for OID subtrees with multi-value results.

I am trying to snmpwalk a switch ARP table (a long list of IP addresses and MAC addresses) querying the OID 1.3.6.1.2.1.3.1.1.2

When querying on command line w/ snmpwalk it runs ok:

	...
	iso.3.6.1.2.1.3.1.1.2.15.1.12.40.13.1 = Hex-STRING: F4 30 B9 F1 C0 5B 
	iso.3.6.1.2.1.3.1.1.2.17.1.12.40.18.1 = Hex-STRING: 70 61 7B 4F D8 70 
	iso.3.6.1.2.1.3.1.1.2.17.1.12.40.18.33 = Hex-STRING: 70 61 7B 4F B8 62 
	...

But when using snmpgo it only yields first result:

snmpgo.VarBinds =>
[
	{
		"Oid": {
		"Value": [
			1,
			3,
			6,
			1,
			2,
			1,
			3,
			1,
			1,
			2,
			15,
			1,
			12,
			40,
			13,
			1
		]
		},
		"Variable": {
		"Value": "......."
		}
	}
]

So, I guess I am doing something wrong when trying to get the full list of items. This is the code used:

package snmplib

import (
	"fmt"

	"github.com/k-sone/snmpgo"
)

func main() {
	IPswitch := "10.31.17.19"
	_Community := "public"
	OID := "1.3.6.1.2.1.3.1.1.2"

	snmp, err := snmpgo.NewSNMP(snmpgo.SNMPArguments{
		Version:   snmpgo.V2c,
		Address:   fmt.Sprintf("%s:161", IPswitch),
		Retries:   1,
		Community: _Community,
	})
	if err != nil {
		// Failed to create snmpgo.SNMP object
		fmt.Println(err)
	}

	oids, err := snmpgo.NewOids([]string{
		OID,
	})
	if err != nil {
		// Failed to parse Oids
		fmt.Println(err)
	}

	if err = snmp.Open(); err != nil {
		// Failed to open connection
		fmt.Println(err)
		return
	}
	defer snmp.Close()

	pdu, err := snmp.GetBulkWalk(oids, 1, 1000)
	if err != nil {
		// Failed to request
		fmt.Println(err)
		return
	}
	if pdu.ErrorStatus() != snmpgo.NoError {
		// Received an error from the agent
		fmt.Println(pdu.ErrorStatus(), pdu.ErrorIndex())
	}

	// get VarBind list
	fmt.Printf("len(pdu.VarBinds()): %d", len(pdu.VarBinds()))
	fmt.Printf("pdu.VarBinds(): %+v", pdu.VarBinds())
}

Any hint? Thx in advance!

**Comment by k-sone** [comment]
I think that the arguments(nonRepeaters and maxRepetitions) are not appropriate.
```diff
-pdu, err := snmp.GetBulkWalk(oids, 1, 1000)
+pdu, err := snmp.GetBulkWalk(oids, 0, 10)
```

Please refer to man snmpbulkget(1) or snmpbulkwalk(1) for these details.

**Comment by computerphysicslab** [comment]
> I think that the arguments(nonRepeaters and maxRepetitions) are not appropriate.
> 
> ```diff
> -pdu, err := snmp.GetBulkWalk(oids, 1, 1000)
> +pdu, err := snmp.GetBulkWalk(oids, 0, 10)
> ```
> 
> Please refer to man snmpbulkget(1) or snmpbulkwalk(1) for these details.

Thanks a lot. It works pretty well now!
