### ISSUE TITLE
SNMPv3 Trap Listener

### ISSUE THREAD

**Issue by initzero** [k-sone/snmpgo#9]
Hello, I've been looking for a nice SNMP lib for awhile and found this. It has a nice feature set, but I am wondering what work needs to be done for v3 trap support. I am interested in helping implement it.

**Comment by k-sone** [comment]
I wrote the V3 Trap Listener(without InformRequest) on [trapv3_receiver](https://github.com/k-sone/snmpgo/tree/trapv3_receiver) branch.
Try it if you like.

**Comment by chacken** [comment]
@k-sone is there a reason that's in a different branch, or has that simply not been merged back yet?

**Comment by k-sone** [comment]
As far as I know, there is a bug in the authentication part.
I'll see if I can fix it this weekend.
